### ISSUE TITLE
Rédaction fichier style

### ISSUE THREAD

**Issue by Abbassihraf** [Abbassihraf/C2N3-Reenforcement#5]
Rédigez les styles de base pour votre projet, y compris les styles de contenu général, tels que "font-family" et "font-size".

- [x] Version Mobile
- [x] Version Desktop

**Comment by Abbassihraf** [comment]
Desktop Version "1.0" done , some changes remain to be worked on in the next few days.

**Comment by youssefbm** [comment]
Good job, add the minor changes in a futur issue

**Comment by Abbassihraf** [comment]
Yes, I will as soon as possible.
